Update automation-container-ee

diff --git a/automation-container-ee b/automation-container-ee
--- a/automation-container-ee
+++ b/automation-container-ee
@@ -1,5 +1,67 @@
 #!/usr/bin/bash
 
+
+
+echo "[I] release: ${AUTOMATION_RELEASE} container: ${CONTAINER_NAME} "${CURRENT_RELEASE:+" (current: ${CURRENT_RELEASE})"}
+
+if [[ ${AUTOMATION_UPDATE} == true ]]
+then
+        if [[ ! -d ${AUTOMATION_PATH} ]]
+        then
+                echo "[I] creating: ${AUTOMATION_PATH}"
+                mkdir ${AUTOMATION_PATH} || echo $?
+        fi
+
+        curl ${AUTOMATION_URL} -o ${AUTOMATION_PATH}/$( basename "${AUTOMATION_URL}" )
+
+        echo "[I] running playbook ${AUTOMATION_PATH}/$( basename ${AUTOMATION_URL} )"
+
+        ANSIBLE_STDOUT_CALLBACK=${ANSBILE_STDOUT_CALLBACK:-'dense'} \
+        ANSIBLE_LOCALHOST_WARNING=False \
+        ansible-playbook \
+                -e "automation_version=${AUTOMATION_RELEASE}" \
+                -e "root_folder=${AUTOMATION_PATH}" \
+                -e "automation_folder=${AUTOMATION_PATH}/automation" \
+                -e "inventory_folder=${AUTOMATION_PATH}/inventory" \
+                ${AUTOMATION_PATH}/$( basename "${AUTOMATION_URL}" )
+
+        if [[ -s ${AUTOMATION_PATH}/versions/.version ]]
+        then
+                REQUIRED_CONTAINER_VERISON=$( <${AUTOMATION_PATH}/versions/.version )
+        fi
+
+fi
+
+if [[ ${LOCAL_ANSIBLE_LOG} == true ]]
+then
+        if [[ ! -d ${LOCAL_ANSIBLE_LOG_PATH} ]]
+        then
+                mkdir ${LOCAL_ANSIBLE_LOG_PATH}
+        fi
+
+        if [[ -h ${LOCAL_ANSIBLE_LOG_PATH} ]]
+        then
+                cd ${LOCAL_ANSIBLE_LOG_PATH}
+                LOCAL_ANSIBLE_LOG_PATH=$PWD
+                cd -
+        fi
+
+        CONTAINER_MOUNTS+=("-v ${LOCAL_ANSIBLE_LOG_PATH}:/home/ansible/ansible-log")
+        EXTRA_EXEC_OPTIONS+=( -e "ANSIBLE_LOG_PATH=/home/ansible/ansible-log/ansible_log_${CONTAINER_NAME}" )
+fi
+
+# Autoselect the container version is specified
+#------------------------------------------------------------
+if [[ -n ${REQUIRED_CONTAINER_VERSION} ]]
+then
+        if [[ $CONTAINER_SELECTED == true ]]
+        then
+                echo "** warning ** you selected container ${CONTAINER_VERSION}, however this release should use ${REQUIRED_CONTAINER_VERSION}"
+        else
+                CONTAINER_VERSION=${REQUIRED_CONTAINER_VERISON}
+        fi
+fi
+
 if [[ ${POD_REMOVE} == true ]]
 then
         name=$( podman ps -a --filter name="${CONTAINER_NAME}\$" -q 2>/dev/null )
