Update git-difftool-vimdiff

diff --git a/git-difftool-vimdiff b/git-difftool-vimdiff
--- a/git-difftool-vimdiff
+++ b/git-difftool-vimdiff
@@ -1,3 +1,11 @@
 #!/bin/bash
 
+working_tree=$( git rev-parse --is-inside-work-tree )
+
+if [[ $working_tree != true ]]
+then
+        echo "error: please run from the root of your git project." 2>&1
+        exit 1
+fi
+
 exec git difftool --tool vimdiff $*
